### ISSUE TITLE
Tracking scope of signals

### ISSUE THREAD

**Issue by Tur8008** [solid-courses/solidjs-the-complete-guide#4]
Hello,
I was glad to find some theoretical materials about reactivity in Solid. Thank's a lot.  
Could you explain please the thing I find quite controversial.

You give the definition of signals on p. 25

> Solid uses signals for reactive data. The concept of a signal is quite simple: It is a wrapper around a regular JavaScript value that keeps a list of subscribers which are notified whenever the value changes. 

and then write about tracking scope of Effects such the words

>Signals are tracked within a tracking scope. A tracking scope is a function scope that is created by an effect. It’s just a regular JavaScript function scope but it’s created by createEffect.

I got this like once a signal  has been read within createEffect or JSX that the effect is put as subscriber into the signal. And when the signal's state changed all the subscribers are launched apply the updated state. I can't get how come signals are tracked within Effects if each Signal stores its subscribers and it reacts of its state changes and then triggers all the updates?

P.S. I didn't find discussions in this repo so I opened the issue.

**Comment by snnsnn** [comment]
I've restructure the part of the book that explains how reactivity works in a way to make it more clear. Let me share the related paragraphs:

Solid uses signals for reactive data. The concept of a signal is quite simple: It is a wrapper around a regular JavaScript value that keeps a list of subscribers which are notified whenever the value changes.

To create a signal, we import the `createSignal` function into the current module and call it with an initial value:

```typescript
import { createSignal } from "solid-js";

const [getCount, setCount] = createSignal(0);
          ↑          ↑
//     accessor    setter
```

`createSignal` returns an array with two items: a getter and a setter. The getter function, commonly referred to as the signal accessor, retrieves the stored value, while the setter function updates it.

We use array destructuring to extract them onto local variables.

Note: This mid part is removed for brevity.

Signals are tracked within a tracking scope. A tracking scope, also known as a reactive context, is a function scope created by `createEffect` or similar functions from the core module that can create subscribers to monitor reactive values. These subscribers are designed to perform specific tasks, such as running side effects, and are deeply integrated into the reactive system.


```ts
import { createEffect } from "solid-js";

createEffect(() => {
  console.log(getCount());
});
```

`createEffect` creates an effect that is called whenever the signal updates. The callback function we pass to `createEffect` needs to read the signal in order to subscribe to it. Subscription takes place automatically upon reading the signal.

Since `getCount` is a function, we had to call it to retrieve the value.

Solid uses a naming convention for the getter functions that do not include the get prefix, for example, `count` instead of `getCount`.

While this convention may be confusing at first, it is an intentional design choice that promotes clear and concise variable names. The benefit becomes more apparent when we introduce the concept of derived signals which are pure functions that transform reactive values.

```ts
const double = () => count() * 2;
```

Note that `double` is not a reactive value itself but recalculates its value each time it is called. When used within a reactive scope, like in `createEffect`, it re-runs its transformation whenever the effect re-executes:

```ts
createEffect(() => {
  console.log(double());
});
```

Hope this clarifies what a reactive scope is.

> I can't get how come signals are tracked within Effects if each Signal stores its subscribers and it reacts of its state changes and then triggers all the updates?

 The dynamics between an effect and a signal is explained in Chapter 4: How Solid’s Reactive System Works . The core reactive logic is re-implemented in that chapter, you can take a look at it how signal collects subscribers.

I will update the book soon.

**Comment by Tur8008** [comment]
It's better now but still burns my brain:) It's quiet confusing topic itself. I've just got to Chapter 4 and I hope it'll clarifies the things more. As read the stuff before I was imaging the process like a Signal gets its subscribers once it has been read within  any reactive scope like createEffect or JSX. I supposed that signals use some of js tools for doing introspections (to track they are being read for example) and that's it. So, when I was reading the place about signals are being tracked within effects I just got confused because of why createEffect is needed to track something :) Now I see that createEffect do the job to create some reactive scope  -- make subscriptions, create working context, may be do some optimization job. I understand that the things is way complex in fact. 
P.S. Thank you for the answer!
